/*
 * Copyright (c) 2015, Netherlands Forensic Institute
 * All rights reserved.
 */
package nl.minvenj.nfi.raqet.jna.libiscsi;

public interface ScsiSenseAscq {
    int SCSI_SENSE_ASCQ_SANITIZE_IN_PROGRESS = 0x041b;
    int SCSI_SENSE_ASCQ_WRITE_AFTER_SANITIZE_REQUIRED = 0x1115;
    int SCSI_SENSE_ASCQ_PARAMETER_LIST_LENGTH_ERROR = 0x1a00;
    int SCSI_SENSE_ASCQ_MISCOMPARE_DURING_VERIFY = 0x1d00;
    int SCSI_SENSE_ASCQ_MISCOMPARE_VERIFY_OF_UNMAPPED_LBA = 0x1d01;
    int SCSI_SENSE_ASCQ_INVALID_OPERATION_CODE = 0x2000;
    int SCSI_SENSE_ASCQ_LBA_OUT_OF_RANGE = 0x2100;
    int SCSI_SENSE_ASCQ_INVALID_FIELD_IN_CDB = 0x2400;
    int SCSI_SENSE_ASCQ_LOGICAL_UNIT_NOT_SUPPORTED = 0x2500;
    int SCSI_SENSE_ASCQ_INVALID_FIELD_IN_PARAMETER_LIST = 0x2600;
    int SCSI_SENSE_ASCQ_WRITE_PROTECTED = 0x2700;
    int SCSI_SENSE_ASCQ_BUS_RESET = 0x2900;
    int SCSI_SENSE_ASCQ_POWER_ON_OCCURED = 0x2901;
    int SCSI_SENSE_ASCQ_SCSI_BUS_RESET_OCCURED = 0x2902;
    int SCSI_SENSE_ASCQ_BUS_DEVICE_RESET_FUNCTION_OCCURED = 0x2903;
    int SCSI_SENSE_ASCQ_DEVICE_INTERNAL_RESET = 0x2904;
    int SCSI_SENSE_ASCQ_TRANSCEIVER_MODE_CHANGED_TO_SINGLE_ENDED = 0x2905;
    int SCSI_SENSE_ASCQ_TRANSCEIVER_MODE_CHANGED_TO_LVD = 0x2906;
    int SCSI_SENSE_ASCQ_NEXUS_LOSS = 0x2907;
    int SCSI_SENSE_ASCQ_MODE_PARAMETERS_CHANGED = 0x2a01;
    int SCSI_SENSE_ASCQ_CAPACITY_DATA_HAS_CHANGED = 0x2a09;
    int SCSI_SENSE_ASCQ_THIN_PROVISION_SOFT_THRES_REACHED = 0x3807;
    int SCSI_SENSE_ASCQ_MEDIUM_NOT_PRESENT = 0x3a00;
    int SCSI_SENSE_ASCQ_MEDIUM_NOT_PRESENT_TRAY_CLOSED = 0x3a01;
    int SCSI_SENSE_ASCQ_MEDIUM_NOT_PRESENT_TRAY_OPEN = 0x3a02;
    int SCSI_SENSE_ASCQ_INQUIRY_DATA_HAS_CHANGED = 0x3f03;
    int SCSI_SENSE_ASCQ_INTERNAL_TARGET_FAILURE = 0x4400;
    int SCSI_SENSE_ASCQ_MEDIUM_LOAD_OR_EJECT_FAILED = 0x5300;
    int SCSI_SENSE_ASCQ_MEDIUM_REMOVAL_PREVENTED = 0x5302;
}